[colors]
[colors.primary]
background = "#1e1e2e"
foreground = "#ffffff"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#cdd6f4"

[colors.bright]
black   = "#989ab0"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#cba6f7"
cyan    = "#94e2d5"
white   = "#ffffff"

[colors.cursor]
text   = "#1e1e2e"
cursor = "#ffffff"
